apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}
spec:
  ports:
  - port: 8081
    targetPort: 8081
    nodePort: 30081
    protocol: TCP
    name: "service-a"
  selector:
    app: {{ .Values.appName }}
    tier: backend
  type: NodePort
